name:                battleship
version:             0.1.0.0
github:              "tina80lvl/battleship"
license:             BSD3
author:              "Valentina Smirnova"
maintainer:          "tinanight98@gmail.com"
copyright:           "2019 Valentina Smirnova"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tina80lvl/battleship#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  battleship-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battleship

tests:
  battleship-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - battleship
